### ISSUE TITLE
App would not start if Montage Data is used without OfflineService

### ISSUE THREAD

**Issue by marchant** [montagejs/montage#1885]
_From @rayshan on February 3, 2016 16:25_

1. Define a main service like below with the `ParentService` child service subclassing `HttpService` and fetches data:
   
   ``` js
   exports.MainService = DataService.specialize({}, /** @lends MainService */ {
       instance: {
           get: function () {
               var instance = this._instance;
               if (!instance) {
                   instance = this._instance = new this();
                   instance.addChildService(new ParentService());
                   // instance.addChildService(new OfflineService());
               }
               return instance;
           }
       }
   });
   ```
2. Start app

Expected: app should start
Actual: app doesn't start, below error stack is shown in console:

``````
```
Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at Anonymous.exports.DataService.Montage.specialize._findOfflineService.value (http://localhost:4000/node_modules/montage-data/logic/service/data-service.js:191:37)
    at Anonymous.exports.DataService.Montage.specialize._offlineService.get (http://localhost:4000/node_modules/montage-data/logic/service/data-service.js:181:46)
    at Anonymous.exports.DataService.Montage.specialize.fetchData.value (http://localhost:4000/node_modules/montage-data/logic/service/data-service.js:1067:61)
    at Anonymous.exports.MainController.Montage.specialize.willFinishLoading.value (http://localhost:4000/logic/main-controller.js:142:26)
    at Application.Montage.defineProperty.value (http://localhost:4000/node_modules/montage/core/core.js:1092:41)
    at eval (http://localhost:4000/node_modules/montage/core/application.js:447:26)
    at r (http://localhost:4000/node_modules/montage/node_modules/bluebird/js/browser/bluebird.min.js:31:5015)
… more bluebird stuff
```
``````

Note: workaround is to add OfflineService as a child service; the downside app will continue to ping a GitHub URI to check connectivity, and if device is offline, lots of console errors are shown.

_Copied from original issue: montagestudio/montage-data#4_

**Comment by marchant** [comment]
_From @hthetiot on April 12, 2017 19:2_

Need OfflineService spec

- https://github.com/montagestudio/montage-data/blob/master/test/spec/offline-service.js#L5
