### ISSUE TITLE
Loader.reel problem while learning Montage Studio. Forum seems abandoned. Where now ?

### ISSUE THREAD

**Issue by CoolGames** [montagejs/montage#1914]
I have left a question at the [FORUM](http://forum.montagestudio.com/t/no-activity-in-over-a-year-beginning-learner-needs-help/125) but see no activity for more than a year.
Where is the most recent and work docs to learn Montage Studio ?

I just restarted to explore it's functionality while learning to code HTML5 toward WebVR.
Here is the jist of the forum post.
```

Chrome developer tools and source index.html reference to "loader reel" 
are not located in my project or /usr/local/lib/node_modules/minit/ directories .

Where is the loader reel expected to be found ?

user-agent = "npm/3.5.2 node/v6.11.4 linux x64"

{
    "owner": {
        "prototype": "montage/ui/loader.reel"
    }
}


```

**Comment by CoolGames** [comment]
Just found the repository to [UPGRADE NodeJS](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
so now at latest released version
`
 user-agent = "npm/5.5.1 node/v9.2.0 linux x64"

$ sudo npm install -gq minit@latest
/usr/bin/minit -> /usr/lib/node_modules/minit/minit
+ minit@0.5.7
updated 1 package in 2.11s



`
NOW, I can't even create an app as before

`$ minit create:app -n tempcore
(node:16442) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/usr/local/lib/node_modules/minit/node_modules/q-io/node_modules/q/q.js:126
                    throw e;
                    ^

TypeError: Cannot convert object to primitive value
    at String.replace (<anonymous>)
    at Object.value (/usr/local/lib/node_modules/minit/lib/template-base.js:238:35)
    at Object.processDirectory (/usr/local/lib/node_modules/minit/lib/template-base.js:180:25)
    at Object.processDirectory (/usr/local/lib/node_modules/minit/lib/template-base.js:204:25)
    at /usr/local/lib/node_modules/minit/lib/template-base.js:131:33
    at _fulfilled (/usr/local/lib/node_modules/minit/node_modules/q-io/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/minit/node_modules/q-io/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/minit/node_modules/q-io/node_modules/q/q.js:760:13)
    at /usr/local/lib/node_modules/minit/node_modules/q-io/node_modules/q/q.js:574:44
    at flush (/usr/local/lib/node_modules/minit/node_modules/q-io/node_modules/q/q.js:108:17)
`

**Comment by hthetiot** [comment]
The current release 17.x.x only support Node <=4.8.x and Npm <=2.x

We are working on finishing 17.1.1 release (see 17.1.1-rc1) then we going to merge the NodeJs 4+ and Npm 3+ support from commonjs branch.

You should be able to test the NodeJs 8 support in the 18.0.0-alpha branch. 

Note: NodeJS 5 is not LTS, version. 18 will support officially 4,6 and 8 with associated npm versions.
